### ISSUE TITLE
rad push failed

### ISSUE THREAD

**Issue by alextes** [radicle-dev/radicle-cli#120]
How do I go about debugging a failed push?

```sh
❯ rad push
Pushing 🌱 to remote `rad`
$ git push rad
Everything up-to-date

Git version 2.36.1
Select a seed node to sync with...
Selected pine.radicle.garden
== Push failed git signing key is not properly configured
==
```

I grabbed an existing git repo, installed radicle-cli using the "cargo install from git" command. Ran `rad init`, filled out the info, then ran `rad push` and selected `pine.radicle.garden` and hit the error above.

**Comment by cloudhead** [comment]
Hey :wave: - Did you run `rad auth`?

**Comment by alextes** [comment]
That did it @cloudhead 👍 .

Now I forget why I confidently ran `push` after `init`. Could it be the UI or CLI suggested doing so without mentioning `auth`? Did I simply read over it maybe?

**Comment by cloudhead** [comment]
You must have run `rad auth` previously, but somehow the signing key was not properly configured. Strange.

Could it be that when you initially ran `rad auth`, the flow got aborted?

**Comment by alextes** [comment]
Oooh, yea I installed radicle a long time ago. It's possible! I definitely don't remember what I did when I originally installed.

**Comment by cloudhead** [comment]
Cool yeah that explains it :)
