### ISSUE TITLE
common: Add `Deserialize` and `Serialize` to `Identifier`

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-cli#187]
I would benefit in `radicle-client-services/http-api`, if I could serialize and deserialize this enum from a string, IMO if we would check if it's only a prefix or a full `git2::Oid` we should be able to do just that.
Am I missing something? Else would implement it in a PR.

https://github.com/radicle-dev/radicle-cli/blob/ea07d1c1327fd05e7792b771436744d415bf4fd9/common/src/cobs/shared.rs#L64

**Comment by cloudhead** [comment]
Yeah, the code is basically there already (`FromStr` and `Display`), do you specifically need serde support?

**Comment by sebastinez** [comment]
Closing this, since it's not relevant anymore
