### ISSUE TITLE
Install by apt: "doesn't support architecture 'i386'"

### ISSUE THREAD

**Issue by chatch** [radicle-dev/radicle-cli#207]
Installing radicle-cli from apt as per the instructions here: https://app.radicle.network/alt-clients.radicle.eth/rad:git:hnrkmg77m8tfzj4gi4pa4mbhgysfgzwntjpao/tree 

At the end of `apt update` I see:
```
N: Skipping acquisition of configured file 'main/binary-i386/Packages', as repository 'https://europe-west6-apt.pkg.dev/projects/radicle-services radicle-cli InRelease' doesn't support architecture 'i386'
```

It wasn't clear to me at first but this is just a warning. I was able to go ahead and install the `amd64` package. But it might be nice to consider supporting this architecture or at least documented you may see the error and it can be ignored.

**Comment by chatch** [comment]
Discovered this error can be suppressed by adding `[arch=amd64]` to  `/etc/apt/sources.list.d/radicle-registry.list` to:
```
deb [arch=amd64] https://europe-west6-apt.pkg.dev/projects/radicle-services radicle-cli main
```

Docs could be updated to use this.

**Comment by adaszko** [comment]
> Discovered this error can be suppressed by adding `[arch=amd64]` to `/etc/apt/sources.list.d/radicle-registry.list`:
> 
> ```
> deb [arch=amd64] https://europe-west6-apt.pkg.dev/projects/radicle-services radicle-cli main
> ```
> 
> Docs could be updated to use this.

This is helpful, thank you!  I'll test it and see to it that the docs are updated 👍
