### ISSUE TITLE
Can't install the CLI on macOS M1 via brew

### ISSUE THREAD

**Issue by msavitskiy** [radicle-dev/radicle-cli#209]
➜  ~ brew tap radicle/cli https://seed.alt-clients.radicle.xyz/radicle-cli-homebrew.git
➜  ~ brew install radicle-cli
==> Downloading https://github.com/radicle-dev/radicle-cli/releases/download/v0.6.0/radicle-cli-x86_64-apple-darwin.tar.gz
Already downloaded: /Users/x/Library/Caches/Homebrew/downloads/092a30ff17335a34a88a1f14c4622aaf9d24580ab7ef913cc053eac188034475--radicle-cli-x86_64-apple-darwin.tar.gz
Error: radicle-cli: SHA256 mismatch
Expected: 6f0afb72a8630e3e7f331f1e74c80ba64d7918320d9234aff8acadd79ab68459
  Actual: acf802221d2afe021d86e9330fc0d09a3400de4b3a8120e3a9303c68afe8f617
    File: /Users/x/Library/Caches/Homebrew/downloads/092a30ff17335a34a88a1f14c4622aaf9d24580ab7ef913cc053eac188034475--radicle-cli-x86_64-apple-darwin.tar.gz
To retry an incomplete download, remove the file above.

**Comment by adaszko** [comment]
Thank you for reporting @msavitskiy.  It's being taken care of.  We'll post a comment here once it's fixed.

**Comment by drgorillamd** [comment]
I just tried today and the tap has been updated, `brew install radicle-cli` now works like a charm @msavitskiy
Thank you @adaszko

**Comment by adaszko** [comment]
Great to hear it's working!  I'm gonna close the issue.  Please comment/create a new issue if you still experience any problems
