### ISSUE TITLE
Fatal: no signers found: ssh-agent is not running

### ISSUE THREAD

**Issue by talentlessguy** [radicle-dev/radicle-cli#210]
Whenever I try to push a repository to Radicle it keeps throwing this error:

```
➜ git push rad
Fatal: no signers found: ssh-agent is not running
```

here's my info:

```
project id: rad:git:hnrkeh5cgjcyq3prdx4it8ynx3zrs3qs7shdo
URN: rad:git:hnrkb9iwxg8cyr9ekzfypeyadpdtzkyoii5to
OS: Linux 5.10
rad 0.6.0
ssh: OpenSSH 9.0
```

**Comment by MFaiqKhan** [comment]
turn on ssh agent run this command  
`
eval `ssh-agent -s`
`
then rad auth to add the keys in the ssh agent . 
have to do it everytime you open a session on linux

**Comment by MFaiqKhan** [comment]
> turn on ssh agent run this command ``eval `ssh-agent -s` ``  
then rad auth to add the keys in the ssh agent . 
have to do it everytime you open a session on linux

**Comment by talentlessguy** [comment]
Oh thank you, but now I have this error: https://github.com/radicle-dev/radicle-cli/issues/192
