### ISSUE TITLE
[FEATURE] Add environment variable support for `rad auth` 

### ISSUE THREAD

**Issue by JoshuaTrujillo15** [radicle-dev/radicle-cli#213]
## Overview

The `rad auth` command requires authentication via an interactive terminal. Using the `--init` option allows `--passphrase` and `--name`, but passing such variables into the command line is considered insecure (as the CLI notifies you).

Using default environment variables such as `RAD_PASSPHRASE` as an alternative to command line arguments and interactive prompts would enable more automation workflows.

## Requested Feature

Add the following environment variables to the `rad auth` crate.

- `RAD_PASSPHRASE`
- `RAD_NAME` (for initializing new profiles)
- `RAD_PROFILE` (for authenticating existing profiles)

**Comment by pinkforest** [comment]
thx :)

**Comment by cloudhead** [comment]
`RAD_PASSPHRASE` and `RAD_PROFILE` makes sense to me, but I don't understand the usecase of `RAD_NAME`?

**Comment by JoshuaTrujillo15** [comment]
`RAD_NAME` is mostly for the sake of completeness.

Name is used when creating an account, which isn't likely to be part of much (if any) automation, but it is a flag (`--name`) when initializing a new profile, so it made sense to just have an env option.

Though I'm not hard-committed to this one, mostly just `RAD_PASSPHRASE` and `RAD_PROFILE`.

**Comment by cloudhead** [comment]
Cool, yeah I'd like to keep env vars to a minimum, so would stick with the two most useful ones.

**Comment by gsaslis** [comment]
+1 this would also help with profile management on the IDE, where we want to script the call to `rad auth`

**Comment by erak** [comment]
I'll look into this.
