### ISSUE TITLE
git2 Dependency OpenSSL

### ISSUE THREAD

**Issue by pinkforest** [radicle-dev/radicle-cli#218]
git2 dependency wants to bring OpenSSL by default features or where feature ssh is explicitly on that brings it

It seems we've needed it via authorized-keys ? might be best to refactor it out so we don't rely on OpenSSL

```
common/Cargo.toml:git2 = { version = "0.13", default-features = false, features = ["https"] }
authorized-keys/Cargo.toml:git2 = "0.13.20"
```

When people are building from source they get often confused by this - especially on modern macOS - and often we just provide them `--vendored-openssl` that we can use to trigger git2/vendored-openssl feature (that triggers the use of [openssl-src crate)](https://crates.io/crates/openssl-src) if we need that lib - or we can just document the needed sys dependencies like here - if we need git2/ssh:

https://github.com/sfackler/rust-openssl/blob/master/openssl/src/lib.rs#L31

**Comment by cloudhead** [comment]
We use ssl to query remote refs in the `track` command, IIRC. Basically, `git2` relies on it when using the HTTPS transport to query a remote git server. If there's a way around that, we can remove it.

**Comment by pinkforest** [comment]
reqwest uses native TLS from system, OpenSSL has it's downsides 

I added a PR to make it vendored so we ensure that latest OpenSSL gets dragged into the build automatically: https://github.com/radicle-dev/radicle-cli/pull/246
