### ISSUE TITLE
Error: rad-clone: unexpected input length: 0

### ISSUE THREAD

**Issue by daharon** [radicle-dev/radicle-cli#224]
I just installed the Radicle CLI and was going through the [guide](https://docs.radicle.xyz/using-radicle/clone).
When cloning according to the example, I get the following error:
```
$ rad clone rad://willow.radicle.garden/hnrkmkfqk1yadewcgasm1s6mp5pn1hc5ch6wy
== Error: rad-clone: unexpected input length: 0
```

**Comment by slack-coder** [comment]
Hi @daharon, for following the guide I recommend using the latest stable release which of now is [v0.6.1](https://github.com/radicle-dev/radicle-cli/releases/tag/v0.6.1).

**Comment by daharon** [comment]
Thanks, @slack-coder.
I installed version 0.6.1 and now I get a new error:
```
$ rad clone rad://willow.radicle.garden/hnrkmkfqk1yadewcgasm1s6mp5pn1hc5ch6wy
== Cloning failed the key for hydrwbfupx1ygrtetwdbkm7eigcx16xckjcy7x4fwocjqbcce3a1ig is not in the ssh-agent, consider adding it via `lnk profile ssh add`
```

**Comment by slack-coder** [comment]
It looks like you are not authenticated, try running 'rad auth' beforehand?

You will need `ssh-agent` running for this, and an [identity created](https://docs.radicle.xyz/getting-started#create-your-radicle-identity).

**Comment by daharon** [comment]
Yes, I needed to re-authenticate with `rad auth`.
Cloning worked.  Thanks for the help.
