### ISSUE TITLE
Users who download from source can't find their projects

### ISSUE THREAD

**Issue by amoweolubusayo** [radicle-dev/radicle-cli#226]
From a Linux user(Manjaro)

after `rad push` the CLI returns a bunch of URLs `Your project is available at: <list of URLs>`, if any of those URLs are clicked, Page returns `Project not found`

**Comment by amoweolubusayo** [comment]
@slack-coder rad v0.6.0

**Comment by slack-coder** [comment]
Hi @amoweolubusayo, I checked this here with the '0.6.1' release.  Could you post the command's terminal output after pushing a project?

**Comment by amoweolubusayo** [comment]
Hello @slack-coder , 

```
Syncing 🌱 identity rad:git:<your radicle id> with <some number> seed

ok Syncing...

🍃 Your project is available at URL
```

It goes through successfully but clicking on the URL, brings up a ‘project not available’

**Comment by slack-coder** [comment]
Hi @amoweolubusayo, being able to see the full output will help.  We can setup a temporary ID for this.  Can you show me the output after running the commands below?

```
export RAD_HOME=/tmp/rad_home

rad auth --init

git init test-project
cd test-project
echo "test project" > README
git add README
git commit -a -m 'initial commit'

rad init .
rad push
```
You should run 'unset RAD_HOME' after to go back to using your old rad ID.

**Comment by amoweolubusayo** [comment]
I would revert back on this. It was a complain of one of the devs in the community

**Comment by amoweolubusayo** [comment]
@vaasanthk please can you state the issue you are having. I know you are using Ubuntu this time and your git version is >2.34

**Comment by erak** [comment]
Hey @amoweolubusayo and @vaasanthk, I fear that you might experience this behaviour because of a non-release build that is not compatible with the network, as @slack-coder also stated.

Did you follow the instructions on https://radicle.xyz/get-started.html or was it build from source?

**Comment by vaasanthk** [comment]
@amoweolubusayo @erak I followed the steps provided here https://radicle.xyz/get-started.html even then I got this issue project could not be found. This is the screenshot 
![Screenshot from 2022-08-31 21-16-59](https://user-images.githubusercontent.com/41782835/187924880-98f55b8b-f963-4791-9660-0183059424e0.png)

**Comment by amoweolubusayo** [comment]
@IdoiaRojoLazaro has same issue now.

**Comment by slack-coder** [comment]
@vaasanthk which 'rad' commands are you using?  You can check this on the command line using the 'which' command.
For me, but for you it should be elsewhere if you used the install method from radicle.xyz/getting-started.html.
```
which rad
# /home/slack-coder/.cargo/bin/rad
```

We are migrating towards https://radicle.xyz/get-started.html, but the [other install instructions](https://docs.radicle.xyz/getting-started) have been corrected.  You can use that too:

```
cargo install radicle-cli --force --locked --git https://github.com/radicle-dev/radicle-cli.git --tag v0.6.1
rad --version
# rad 0.6.1
```

Also, if possible, please paste the text output instead of screenshots.  It will help us diagnose the problem.

**Comment by IdoiaRojoLazaro** [comment]
`
which rad
/Users/idoia/.cargo/bin/rad
`
`rad --version
rad 0.6.0`

**Comment by slack-coder** [comment]
> I've tried with the command you sent and I have some errors:
> 
> ```
> failed to compile `radicle-cli v0.6.1 (https://github.com/radicle-dev/radicle-cli.git?tag=v0.6.1#1e6ed9b8)`, 
> intermediate artifacts can be found at `/var/folders/4w/1gsq6kmn1c9__xzty265g0v40000gn/T/cargo-install8EUqd7`
> ```

@IdoiaRojoLazaro this looks like a separate issue.  Maybe create a new issue for it?

I recommend uninstalling the cargo crate, and following the install instructions from the new [getting started guide](https://radicle.xyz/get-started.html).  I've updated my previous comment with instructions on how to do this.

**Comment by vaasanthk** [comment]
@slack-coder Thank you very much; after following the steps you provided, it is now working, and I can see the repo.

**Comment by amoweolubusayo** [comment]
Great. Closing this now.

**Comment by IdoiaRojoLazaro** [comment]
@slack-coder thank you so much, after uninstalling the cargo crate is working!!

**Comment by amoweolubusayo** [comment]
Glad to know! Thanks for all help @slack-coder and @erak!
