### ISSUE TITLE
SSH error on Ubuntu when doing rad push

### ISSUE THREAD

**Issue by Amtaf** [radicle-dev/radicle-cli#243]
Even after doing updates im still getting errors

<img width="461" alt="ssh error" src="https://user-images.githubusercontent.com/9764833/187981716-3029d8d9-8d19-4ade-8b77-df24c4570d9a.png">

**Comment by erak** [comment]
Hey @Amtaf  :wave: It looks like your trying to sign with an older version of openssh. Could you try updating to at least the version that's mentioned in the error, so >=8.2?

**Comment by Amtaf** [comment]
Thank you so much had to update the SSH version to 8.2p1 it worked on Ubuntu,I think it should be added as a prerequisite to use that version.

**Comment by erak** [comment]
@Amtaf Closing this now. Please reach out if you're experiencing any other issues.

**Comment by cloudhead** [comment]
Closing, and since we're bundling openssl now, it shouldn't come back.
