### ISSUE TITLE
`rad-init` does not accept path to git repo 

### ISSUE THREAD

**Issue by gsaslis** [radicle-dev/radicle-cli#30]
## What Happened

```bash
./rad-init ~/some-path-to-git-repo/
== Error: rad-init: unexpected argument "/Users/gsaslis/some-path-to-git-repo"
```

## What Should Happen 

I would expect that I could invoke `rad-init` passing it a path to be initialized (and not always assume the current working directory). 

## Notes

Just a nice to have feature - but something I wanted to make a note of somewhere. ;)

**Comment by cloudhead** [comment]
Fixed in 8c824eab6fdbb0af184ebd41e74a82fec2949714
