### ISSUE TITLE
Confusion on `username` vs. `name` terminology

### ISSUE THREAD

**Issue by gsaslis** [radicle-dev/radicle-cli#66]
On `rad auth --init`, the prompt asks for a `username`. 

On `rad self`, the "profile" information shown, lists a `name`. 

It seems these are both referring to the same field and it would be good to agree which of the two terms should be used.

**Comment by erak** [comment]
Hey @gsaslis, thanks for the report! I think it should be `name`, as that's the term we seem to use usually. I opened https://github.com/radicle-dev/radicle-cli/pull/68, which fixes this.

**Comment by gsaslis** [comment]
Frankly, I'm not sure which of the two it should be.

Is the "Name" meant to offer some description of the "profile"?

Also, do I understand correctly that "profile" is another name for "Device ID" (but not Peer ID)?

As part of the radicle grant on UX research on the IDE plugins we were trying to clarify the terms and there was quite some confusion between us... (especially since "account" is reserved for ethereum...)

**Comment by gsaslis** [comment]
@erak / @cloudhead thanks for taking care of this! 👍🏼  

any thoughts on the questions above? looking for a glossary, I came across https://docs.radicle.xyz/docs/understanding-radicle/glossary#display-name and I'm wondering if `display-name` would be the clearer term (that also stays in line with the docs).

**Comment by cloudhead** [comment]
@gsaslis DeviceID is the old term for PeerID. Profile is a local radicle environment which comprises of monorepo, peer-id and identity.

**Comment by gsaslis** [comment]
Thanks @cloudhead !

I'm wondering what you all think: should I perhaps create a different issue for renaming `name` to `display-name` to match the docs, or whether it is the docs that should be updated? (Personally I prefer `display-name`, but even more than that I prefer consistency, so I'm happy if either fix is applied).

**Comment by gsaslis** [comment]
p.s. happy to open the PR btw

**Comment by cloudhead** [comment]
"Name" is the correct term as per the spec https://github.com/radicle-dev/radicle-link/blob/1294f738a616cef08ab97a2efa8b7626c059121e/docs/spec/sections/identities.adoc#doc-payload where it is described as a "short name".

**Comment by gsaslis** [comment]
hmmm I think I'm a bit more confused now. 😅

I thought the name vs. display-name discussion above was about the radicle "profile", which, as far as I understand it, is the PeerID. This link seems to be referring to the `name` field for the `Person` entity. It is my understanding that a `Person` may have multiple PeerIDs (a.k.a. profiles?) and each of those profiles would have a different `name` , while the `Person` would always have a single `name` ?

**Comment by cloudhead** [comment]
A PeerID is just a public key, it doesn't have a name. Only Persons have names.

**Comment by gsaslis** [comment]
The plot thickens. 😅 

When I `rad auth --init`, I am told that I am creating a "profile". Until my previous message, I understood that was a PeerID. 
However, if the PeerID doesn't have a `name`and only a `Person` does, then it sounds like `rad auth --init` is creating both a `Person` **and** a `PeerID` ? 🤔  (In which case, can a `Person` not have multiple keys / PeerIDs ? )

**Comment by cloudhead** [comment]
When you create a new radicle profile, you create:
* A peer-id for this device
* A personal identity for you as a user, with the peer-id as signer
* A storage for all git objects
* A profile which encapsulates all of the above

A person can have multiple peer-ids/keys/devices, yes.
