### ISSUE TITLE
Running `rad auth` without `--init` flag, creates partial identity

### ISSUE THREAD

**Issue by christroutner** [radicle-dev/radicle-cli#81]
I'm running radicle-cli on a Ubuntu 18.04 system. I've documented my issues with installing and working with radicle-cli, as well as the upgrades I've needed to make in order to make it work, on [my radicle research page](https://christroutner.github.io/trouts-blog/docs/censorship/radicle/).

When I run `rad push` I'm getting this error:

```
== Push failed
Fatal: no rad/self present and no default identity configured
error: failed to push some refs to 'rad://hnrkjsnux9ns5t4famcga7f4r64a1brh99y1o.git'
```

But when I run `rad self` it comes back just fine:

```
trout@trout-vb:~/work/test-repo-03$ rad self
Profile 7fed6439-8623-4c25-bdfb-f5a7fe9651e5
├── Peer ID    hydjmd3ht8erttcrkczxcak78cg7i3dw9xdcsrtusqwwgstry19odk                           
├── Key (hash) SHA256:D8QH/HaO5ZLF51sKT630gnxlRRwl+507Dmzg2lSqSMU                               
└── Key (full) ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINKx55E6CRiwimXezCunYbtcjp942WJGdnUoa0SAl+A1 
```

Same with `rad auth`:

```
trout@trout-vb:~/work/test-repo-03$ rad auth
Your active profile is 7fed6439-8623-4c25-bdfb-f5a7fe9651e5
ok Signing key already in ssh-agent
ok Signing key configured in git
```

Any idea what could be causing this issue?

**Comment by sebastinez** [comment]
Hi @christroutner, it seems you are missing parts of the `rad self` output.
You should also have a name and urn, e.g.
```
Profile 1649eca5-0794-49b6-8c0d-3d6523ce998a
├── Name       sebastinez
├── URN        rad:git:hnrk81wcokr48mkm544kh74kc9fqz84d3rfcy
├── Peer ID    hyyg555wwkkutaysg6yr67qnu5d5ji54iur3n5uzzszndh8dp7ofue
├── Key (hash) SHA256:5hrJP34ffe3kANws/PaAiXbZXCZu/jB0hIgse2MZusM
└── Key (full) ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA297pRSpxwCxvAJ7rhT2Paa71WZMi3O97XEPhxt7As0
´´´

Did you ran `rad auth --init` in the beginning or how did you create your Radicle identity?

**Comment by christroutner** [comment]
I ran `rad auth`, but not with the `--init` flag. I believe that is how I managed to create an identity with those missing pieces.

Running `rad auth --init` created a second ID. When I ran `rad auth` I then had to choose one of those IDs.

I was able to delete the `~/.config/radicle-link` directory to delete both identities. I was then able to create a single, new identity with `rad auth --init`.

After doing that, I deleted the repository, re-created it with `rad clone`, and after making a change, I was able to successfully commit the change to the repo! You were right, the issue was the missing pieces.

**Comment by sebastinez** [comment]
Interesting. This seems like a bug, I'll reopen the issue and see if we can fix this, or if this is a desired use case.

**Comment by cloudhead** [comment]
Are you able to reproduce this?

**Comment by christroutner** [comment]
Yes, I can reproduce this. I have the state saved to a virtual machine.

I'm running Ubuntu 18.04. The steps I took to setup the environment is captured [in these notes](https://christroutner.github.io/trouts-blog/docs/censorship/radicle).

Here are steps I can do to consistently reproduce this:
- Delete the `~/.config/radicle-link` directory to reset the state.
- Run `rad auth`
- Run `rad self`

I get this output:

```
trout@trout-vb:~/work$ rad auth
Your active profile is 9b242332-a2c3-4894-9ae0-a31c1d897c98
** Adding your radicle key to ssh-agent...
ok Passphrase · ********
ok Unlocking...
ok Radicle key added to ssh-agent
ok Signing key configured in git
trout@trout-vb:~/work$ 
trout@trout-vb:~/work$ rad auth
Your active profile is 9b242332-a2c3-4894-9ae0-a31c1d897c98
ok Signing key already in ssh-agent
ok Signing key configured in git
trout@trout-vb:~/work$ rad self
Profile 9b242332-a2c3-4894-9ae0-a31c1d897c98
├── Peer ID    hybqyc1fsc58x537tsg9k53yqhqwacd5oa4j6j6roqjg1t1bn5q6js                           
├── Key (hash) SHA256:I5mE2JzYtLce2NranqK0+XyinApc9H7NQ6Hb3cmzx/8                               
└── Key (full) ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwGSLZmzv3nsbG+reQO46mGD3DGk+T4kHJNKMgi27yb 
trout@trout-vb:~/work$
```

**Comment by erak** [comment]
Hey @christroutner, I've tried to reproduce with your setup, but couldn't. Was does `rad auth` return for you on a clean state? Could you send that? It should also output the newly created identity:
```
...
Your radicle Peer ID is hynbbstm1nri7jb3jzgqd8qe53rwy5ewj5ccnhi891tmosbtpc14ok. This identifies your device.
Your personal 🌱 URN is rad:git:hnrkka8bq5j9i5p9gjb6b3ma3yjr9xfsyf3my. This identifies you across devices.
...
```

**Comment by christroutner** [comment]
I'm not sure if I can reproduce this with a clean state. It probably doesn't matter, since I was using an older version of Ubuntu 18. New installations will use new OS's. If you're not able to reproduce, then this is probably a corner case that will fade away with time.

I'm going to go ahead and close this Issue. Feel free to reopen it.
